backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
media_folder: public/assets/images/uploads
public_folder: /assets/images/uploads
site_url: "peculiardynamics.co.uk" # your site name
display_url: "https://peculiardynamics.co.uk"
logo_url: /assets/images/350x100.webp

collections:
  - name: blog
    label: Blogs
    label_singular: "Blog Post"
    folder: src/content/blog
    create: true
    delete: true
    format: frontmatter
    preview_path: blog/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text Preview", name: "preview", widget: "string" }
      - {
          label: "Author Name",
          name: "author",
          widget: "string",
          default: "Lucy Chaplin",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Categories",
          name: "categories",
          hint: "Add tags separated by a comma",
          widget: "select",
          multiple: true,
          options:
            [
              "Building Websites",
              "Growing Businesses",
              "Strategy & Success",
              "Tech & Tools",
              "Everything Else",
            ],
        }
      - {
          label: "Tags",
          name: "tags",
          hint: "Add keyword tags separated by a comma",
          widget: "list",
          allow_add: true,
          allow_delete: true,
          summary: "{{fields.tag}}",
          field:
            { label: "Tag", name: "tag", widget: "string", default: ["blog"] },
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Image Caption",
          name: "imageAlt",
          widget: "string",
          required: false,
          hint: "Add a caption if you need to describe this image to visually impaired users, otherwise, leave blank",
        }
      - { name: body, label: Body, widget: markdown }
